config/routes.rb
Rails.application.routes.draw do
  root 'users#new'

  get 'ingredients_recipes/index' => 'ingredients_recipes#index'
  get '/ingredients_recipes/search' => 'ingredients_recipes#search'
  get '/ingredients_recipes/:id' => 'ingredients_recipes#show'
  post '/ingredients_recipes' => 'ingredients_recipes#create'

  post '/user_tries' => 'user_tries#create'
  post '/user_tries/:id' => 'user_tries#edit'

  get 'comments/:ingredients_recipe_id' => 'comments#index'
  post 'comments' => 'comments#create'


  resources :users, only: [:new, :create, :show, :destroy]

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'
end

app/models/comment.rb
# comments.rb
class Comment < ActiveRecord::Base

	belongs_to :ingredients_recipe
	belongs_to :user

end

app/models/comments.rb
# comments.rb
class Comment < ActiveRecord::Base

	belongs_to :ingredients_recipe
	belongs_to :user

end

app/models/ingredients_recipe.rb
# ingredients_recipe.rb
class IngredientsRecipe < ActiveRecord::Base

	has_many :comments
	has_and_belongs_to_many :users
	has_many :user_tries

	API_ROOT = 'http://food2fork.com/api/'

	def self.search(term)
		query_string = [API_ROOT, 'search?key=95fa5272d2a677ab13abe287179a459e&q=', term].join('')

		# query_string = [API_ROOT, 'search?key=a5211143cab0c6434f03db6cbc03268e&q=', term].join('')
		query_string = URI.escape(query_string)
		results = HTTParty.get(query_string)
		return JSON.parse(results)
	end

	def self.search_by_id(id)
		query_string = [API_ROOT, 'get?key=95fa5272d2a677ab13abe287179a459e&rId=', id].join('')

		# query_string = [API_ROOT, 'get?key=a5211143cab0c6434f03db6cbc03268e&rId=', id].join('')
		results = HTTParty.get(query_string)
		return JSON.parse(results)
	end

end

app/models/recipe.rb
class Recipe

	API_ROOT = 'http://food2fork.com/api/'

	def self.search(term)
		query_string = [API_ROOT, 'search?key=95fa5272d2a677ab13abe287179a459e&q=', term].join('')
		# query_string = [API_ROOT, 'search?key=a5211143cab0c6434f03db6cbc03268e&q=', term].join('')
		query_string = URI.escape(query_string)
		results = HTTParty.get(query_string)
		return JSON.parse(results)
	end

	def self.search_by_id(id)
		query_string = [API_ROOT, 'get?key=95fa5272d2a677ab13abe287179a459e&rId=', id].join('')
		# query_string = [API_ROOT, 'get?key=a5211143cab0c6434f03db6cbc03268e&rId=', id].join('')
		results = HTTParty.get(query_string)
		return JSON.parse(results)
	end

end

app/models/user.rb
class User < ActiveRecord::Base

	validates :username, presence: true, uniqueness: true
	has_secure_password
	has_and_belongs_to_many :ingredients_recipes
	has_many :comments
	has_many :user_tries

end

app/models/user_try.rb
class UserTry < ActiveRecord::Base

	belongs_to :ingredients_recipe
	belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   def authenticate
  	redirect_to new_user_path unless session[:current_user_id]
  end

  def current_user
  	User.find(session[current_user_id]) if session[:current_user_id]
  end
end

app/controllers/comments_controller.rb
# comments_controller.rb
class CommentsController < ApplicationController

	def index
		comments = Comment.where(:ingredients_recipe_id => params[:ingredients_recipe_id])
		comments_array = []

		comments.each_with_index do |comment, i|
			comment_hash = comment.as_json
			comment_hash[:username] = comment.user.username
			comment_hash[:avatar_url] = comment.user.avatar_url
			comment_hash[:formatted_date] = comment.created_at.in_time_zone('Eastern Time (US & Canada)').strftime(" %l:%M %p %A, %d %b %Y")
			# comment_hash[:formatted_date] = comment.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("%A, %d %b %Y %l:%M %p")


			comments_array.push({
				username: comment.user.username,
				avatar_url: comment.user.avatar_url,
				comment: comment_hash

				})
			# current_comment = comments_array[i]

			# current_comment["username"] = comment.user.username
		end

		# render json: comments
		render json: comments_array
	end

	def create
		comment = Comment.new(comment_params)
		comment.user_id = session[:current_user_id]
		comment.save
		render json: comment
	end

	def comment_params
		params.require(:comment).permit(:comment, :ingredients_recipe_id)
	end


end

app/controllers/ingredients_recipes_controller.rb
class IngredientsRecipesController < ApplicationController

	def index
		render layout: 'application', text: ''
	end

	def search
		search_results = IngredientsRecipe.search(params[:search])
		@recipes = search_results["recipes"]
		render json: @recipes
	end

	def show
		check = IngredientsRecipe.find_by_f2f_recipe_id(params[:id])

		if check 
			search_results = IngredientsRecipe.search_by_id(check.f2f_recipe_id)
			# binding.pry
			arr = []
			check.comments.each do |c|
				temp = c.as_json
				temp[:username] = c.user.username
				temp[:avatar_url] = c.user.avatar_url
				temp[:formatted_date] = c.created_at.in_time_zone('Eastern Time (US & Canada)').strftime(" %l:%M %p %A, %d %b %Y")

				arr.push temp
			end

			full_data = {recipe: search_results, comments: arr} #before we had check.comments here but it didnt have the username or avatar_url
			render json: full_data
			# binding.pry

		else
			
			search_results = IngredientsRecipe.search_by_id(params[:id])

			full_data = {recipe: search_results, comments: []}
			render json: full_data
		end
	end

	def create
		check = IngredientsRecipe.find_by_f2f_recipe_id(params[:ingredients_recipe][:f2f_recipe_id]
)
		#binding.pry

		if check
			render json: check
		else
			@ingredients_recipe = IngredientsRecipe.new(ingredients_recipe_params)

			@ingredients_recipe.save
			render json: @ingredients_recipe
		end
	end

	def ingredients_recipe_params
		params.require(:ingredients_recipe).permit(:name, :endpoint, :f2f_recipe_id, :f2f_img_url)
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to ingredients_recipes_index_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_path
  end

	

end

app/controllers/user_tries_controller.rb
class UserTriesController < ApplicationController

    def create
        user_try = UserTry.new(user_try_params)
        user_try.user_id = session[:current_user_id]
        user_try.save
        render json: user_try
    end

    def user_try_params
        params.require(:user_try).permit(:try, :ingredients_recipe_id)
    end

    def edit
        user_try = UserTry.find(params[:id])
        user_try.try = false
        user_try.save
        redirect_to '/users/' + session[:current_user_id].to_s
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate, except: [:new, :create]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:current_user_id] = @user.id
			redirect_to ingredients_recipes_index_path
		else
			redirect_to root_path
		end
	end

	def show
		
		@user = User.find(params[:id]);
		@ingredients_recipes = IngredientsRecipe.find(@user.user_tries.pluck(:ingredients_recipe_id))
		
		# @ingredients_recipe = IngredientsRecipe.where(:user_id => (params[:id]))
		# puts @ingredients_recipe
		# puts IngredientsRecipe
		# # # recipes

		# data = {
		# 	user:key => "value",  user,
		# 	user_tries: user_tries
		# }

		# render :json data
	
	end

	def destroy
		@user = User.find(params[:id])
		session[:current_user_id] = nil
		@user.destroy
		redirect_to root_path
	end

	private

	def user_params
		params.require(:user).permit(:username, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredients_recipes/index.html.erb
<div class="container">
	<nav>User Profile</nav>
	
		</div>

	<div id='modal'></div>
		<div id='recipe-list'>

			<div id='search'><%= link_to "Search", ingredients_recipes_index %>
				<input type="text" name='search' id='recipe-search'>
				<button class="search">Search</button>
				<div id='recipes'></div>
			</div>
		</div>

		<div id="goHere">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipesApp</title>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href='http://fonts.googleapis.com/css?family=Delius+Unicase' rel='stylesheet' type='text/css'>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.1/masonry.pkgd.min.js"></script>

      <style type="text/css">
        .grid-item { width: 200px; }
        .grid-item--width2 { width: 400px; }
      </style>

    <%= csrf_meta_tags %>
  </head>
<body>

<div class="container">
  <div class="header vert">
    <div class="navbar navbar-fixed-top navbar-bold" >
    <!--  <nav class="navbar navbar-default navbar-fixed-top" role="navigation"> -->
        <div class="navbar-header">
          <div class="login">
            <% if session[:current_user_id]%>
              <div class="collapse navbar-collapse" id="collapse">
                <h1>Welcome back, <%="#{User.find(session[:current_user_id]).username}"%></h1>
                    <ul class="nav navbar-nav navbar-right" id="navUl">
                      <li><%= link_to "User Profile", user_path(session[:current_user_id])%></li>
                      <li><%= link_to "Logout", sessions_path, method: :delete %></li>
                    </ul>        
              </div><!-- collapse navbar-collapse -->
          </div>
        </div>
    </div>
  </div>
          
  <div id='modal'></div>

  <div class='row col-md-3' id='recipe-list'>
    <div id='search' class="search-wrapper cf">
      <input type="text" type="text" placeholder="Add Ingredients" required="" name='search' id='recipe-search'>

      <button class="search cf">Search</button>

    </div>

    <div class="content container"> 
      <div class="row">
        <div id='recipes'></div>
      </div>
      
    </div>
  </div>

  <% else %>

  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <div class="account-wall">
        <div id="my-tab-content" class="tab-content">
          <p class="container form-signin login-title">Already a Member</p>

          <div class="container">
          <%= form_tag(sessions_path) do%> 

          <%= label_tag :username%>
                         
          <%= text_field_tag :username%>
                         
          <br>
          <%= label_tag :password %>
          <%= password_field_tag :password%>
          <br>
          <%= submit_tag "Login", class: 'btn btn-primary'%>
          </div>
          <% end %>
      <% end %>
      </div>
    </div>
  </div>

  <%= yield %>

</div>

</body>
</html>

app/views/recipes/search.js.erb
<% @recipes.each do |r| %>
	$('#goHere').append("Publisher: <%= r['publisher'] %>")
<% end %>

// publisher
//   "f2f_url"
//   "title"=>"Bacon Double Cheese Burger Dip",
//   "source_url"=>
//    "http://www.closetcooking.com/2012/01/bacon-double-cheese-burger-dip.html",
//   "recipe_id"=>"35107",
//   "image_url"=>
//    "http://stat

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <div class="account-wall">
        <div id="my-tab-content" class="tab-content">
          <p class="container form-signin login-title">Sign Up</p>
          <%= form_for @user do |f|%>
          <%= f.label :username, class: "container"%><br>
          <%= f.text_field :username, class: "form-control form-signin"%><br>
          <%= f.label :password, class: "container"%><br>
          <%= f.password_field :password, class: "form-control form-signin"%><br>
          <%= f.label :password_confirmation, class: "container"%><br>
          <%= f.password_field :password_confirmation, class: "form-control form-signin"%><br>
          <br>
          
          <%= f.submit "Sign Up", class: 'btn btn-primary'%>
          
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- User Profile Display --> 
<div class="container">
  <div id="user-page">
      <!-- Displays anything from users table -->
      <div id="nameOfUser">
        <h1> <%= @user.username %>'s Board</h1>
      </div>

  <div class="leftColumn col-sm-6">
    <h2> Recipes I want to try </h2>

      <% @ingredients_recipes.each do |i| %>
          <% if i.user_tries.first.try == true %>
          <h1><%= i.name %></h1>

          <img src="<%= i.f2f_img_url %>">
            <%= button_to "Tried", '/user_tries/' + i.user_tries.first.id.to_s, :class => "button"  %><br />

          <% end %>
      <% end %>
    </div>

  <div class="rightColumn col-sm-6">
    <h2> Recipes I have tried </h2>

      <% @ingredients_recipes.each do |i| %>
          <% if i.user_tries.first.try == false %>
          <h1><%= i.name %></h1>

          <img src="<%= i.f2f_img_url %>">
          

          <% end %>
      <% end %>
    </div>





  </div>
</div>